[package]
name = "pathfinder_svg"
version = "0.1.0"
authors = ["Sebastian K <s3bk@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.11"
svgtypes = "0.5"
pathfinder_geometry = { path = "../pathfinder/geometry" }
pathfinder_canvas = { path = "../pathfinder/canvas", features = ["pf-simple-text"] }
