[package]
name = "pathfinder_svg"
version = "0.1.0"
authors = ["Sebastian K <s3bk@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.11"
svgtypes = "0.5"
pathfinder_geometry = { path = "../pathfinder/geometry" }
pathfinder_content = { path = "../pathfinder/content" }
pathfinder_renderer = { path = "../pathfinder/renderer" }
pathfinder_color = { path = "../pathfinder/color" }
pathfinder_view = { path = "../pathfinder_view" }
font = { path = "../font" }
lazy_static = "*"

[patch.crates-io]
pathfinder_geometry = { path = "../pathfinder/geometry" }
pathfinder_content = { path = "../pathfinder/content" }
pathfinder_simd = { path = "../pathfinder/simd" }
pathfinder_renderer = { path = "../pathfinder/renderer" }
pathfinder_color = { path = "../pathfinder/color" }

[patch."https://github.com/s3bk/pathfinder"]
pathfinder_geometry = { path = "../pathfinder/geometry" }
pathfinder_content = { path = "../pathfinder/content" }
pathfinder_simd = { path = "../pathfinder/simd" }
pathfinder_color = { path = "../pathfinder/color" }
pathfinder_renderer = { path = "../pathfinder/renderer" }
pathfinder_gl = { path = "../pathfinder/gl" }
pathfinder_resources = { path = "../pathfinder/resources" }
